name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
     
    runs-on: ubuntu-latest
    timeout-minutes: 2 
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker run 21-alpine3.18 && node -v
      
