name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
     
    runs-on: ubuntu-latest
    timeout-minutes: 3 
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker run --name test node:21-alpine3.18 && docker stop test
      
