name: GitHub Actions с Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx

    - name: Проверка конфигурации Nginx
      run: sudo nginx -t

    - name: Запуск Nginx
      run: |
          sudo nginx -g "daemon off;" &
          echo "Nginx запущен"
          sleep 10
          ps aux | grep nginx

